name: Marmite
tagline: Static Site Generator <br> <small>for blogs</small> <br> <small>made with ❤️ and 🦀</small>
url: https://marmite.blog
pagination: 10
enable_search: true
toc: true
json_feed: true
sitemap: true
menu:
  - ['Contributors', 'contributors.html']
  - ["Showcase", "showcase.html"]
  - ['Tags', 'tags.html']
  - ['Archive', 'archive.html']
  - ['Authors', 'authors.html']
  # - ['Streams', 'streams.html']
  - ['Github', 'https://github.com/rochacbruno/marmite/']
card_image: ./media/og_image.jpg
# banner_image: media/og_image.jpg
default_date_format: "%A, %d %B %Y"
publish_md: true
source_repository: https://github.com/rochacbruno/marmite/blob/main/example/content/
# Image provider for automatic image download
image_provider: picsum
extra:
  colorscheme_toggle: true
  # colorscheme: minimal_wb
  social_networks:
    linkedin:
      url: https://www.linkedin.com/in/rochacbruno/
    github:
      url: https://github.com/rochacbruno
    links:
      url: https://bruno.rocha.social

default_author: rochacbruno
authors:
  rochacbruno:
    name: Bruno Rocha
    avatar: https://github.com/rochacbruno.png
    bio: Marmite Maintainer
    links:
      - ["Fediverse", "https://go.rocha.social/@bruno"]
      - ["Github", "https://github.com/rochacbruno"]
      - ["Linkedin", "https://www.linkedin.com/in/rochacbruno/"]
      - ["Links", "https://bruno.rocha.social"]
  karlamagueta:
    name: Karla Magueta
    avatar: https://github.com/karlamagueta.png
    links:
      - ["Github", "https://github.com/karlamagueta"]

# File mapping configuration
file_mapping:
  - source: ai/llms.txt
    dest: llms.txt
  - source: static/favicon.ico
    dest: favicon.ico

# Stream display name mappings
streams:
  alt:
    display_name: "Alternative Stream"
  tutorial:
    display_name: "Tutorials"
  news:
    display_name: "Latest News"
  guide:
    display_name: "User Guides"

# Series display name mappings
series:
  python-tutorial:
    display_name: "Python Tutorial"
    description: "A comprehensive Python programming tutorial series"