name: Marmite SSG
tagline: Simply create a static blog from markdown files
url: https://rochacbruno.github.io/marmite/
pagination: 6
enable_search: true
menu: 
  - ['Docs', 'tag-docs.html']
  - ['Contributors', 'contributors.html']
  - ['Tags', 'tags.html']
  - ['Archive', 'archive.html']
  - ['Github', 'https://github.com/rochacbruno/marmite/']
card_image: ./media/og_image.jpg
extra:
  comments:
    title: Comments
    source: |
      <script src="https://giscus.app/client.js"
              data-repo="rochacbruno/marmite"
              data-repo-id="R_kgDONAKMvQ"
              data-category="Comments"
              data-category-id="DIC_kwDONAKMvc4CjmH_"
              data-mapping="pathname"
              data-strict="0"
              data-reactions-enabled="1"
              data-emit-metadata="0"
              data-input-position="bottom"
              data-theme="dark"
              data-lang="en"
              data-loading="lazy"
              crossorigin="anonymous"
              async>
      </script>
