name: Marmite
tagline: Static Site Generator
url: https://rochacbruno.github.io/marmite
pagination: 5
enable_search: true
toc: true
json_feed: true
menu: 
  - ['Contributors', 'contributors.html']
  - ['Tags', 'tags.html']
  - ['Archive', 'archive.html']
  - ['Authors', 'authors.html']
  # - ['Streams', 'streams.html']
  - ['Github', 'https://github.com/rochacbruno/marmite/']
card_image: ./media/og_image.jpg
# banner_image: media/og_image.jpg
default_date_format: "%A, %d %B %Y"
extra:
  colorscheme_toggle: true
default_author: rochacbruno
authors:
  rochacbruno:
    name: Bruno Rocha
    avatar: https://github.com/rochacbruno.png
    bio: Marmite Maintainer
    links:
      - ["Fediverse", "https://go.rocha.social/@bruno"]
      - ["Github", "https://github.com/rochacbruno"]
      - ["Linkedin", "https://www.linkedin.com/in/rochacbruno/"]
      - ["Links", "https://bruno.rocha.social"]
  karlamagueta:
    name: Karla Magueta
    avatar: https://github.com/karlamagueta.png
    links:
      - ["Github", "https://github.com/karlamagueta"]